# docker-compose.yml (Baza dla DEV)
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      # Ta opcja mówi, żeby budować TYLKO etap "builder"
      target: base 
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    container_name: grafika_gui_dev
    image: grafika-gui-projekt-dev # Inna nazwa obrazu
    volumes:
      - .:/app:rw
    tty: true
